
export const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    Local_img: "/menu/images/06001.jpeg",
    Remote_img: "https://mlybsphqojjqadpysauq.supabase.co/storage/v1/object/public/demo-06/menu/06001.jpeg",
    descrip: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    Local_img: "/menu/images/06002.jpeg",
    Remote_img: "https://mlybsphqojjqadpysauq.supabase.co/storage/v1/object/public/demo-06/menu/06002.jpeg",
    descrip: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "dinner",
    price: 6.99,
    Local_img: "/menu/images/06003.jpeg",
    Remote_img: "https://mlybsphqojjqadpysauq.supabase.co/storage/v1/object/public/demo-06/menu/item-1.jpeg",
    descrip: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    Local_img: "/menu/images/item-4.jpeg",
    Remote_img: "https://mlybsphqojjqadpysauq.supabase.co/storage/v1/object/public/demo-06/menu/item-2.jpeg",
    descrip: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    Local_img: "/menu/images/item-5.jpeg",
    Remote_img: "https://mlybsphqojjqadpysauq.supabase.co/storage/v1/object/public/demo-06/menu/item-3.jpeg",
    descrip: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    Local_img: "/menu/images/item-6.jpeg",
    Remote_img: "https://mlybsphqojjqadpysauq.supabase.co/storage/v1/object/public/demo-06/menu/item-4.jpeg",
    descrip: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
];
